travis:
  secure:
    BINSTAR_TOKEN: ztTg9rbNe0DUgqDRUXwjc9ZkGY7hvqe7nFx5UOIGFxdrFJh3KNeqqyNi6un+uaLSOTXo+03W3HHyFgrjgPZJrtiGut6qLqToyggjNANVrIYyFwyxDd6QkrmwhHlSDWfPf5aqWzYGtRbjaAYUYcFrfQeeydqSiYW1DiZny5uk+QABubnLnzWe2v5SIfUDpnVRdZmSUTiIqDjmmksSMQt+rIMEFH9TxIba8V/pHDkKIKtBglBtFPGSAFehSNCqEhspHuQ9obC1YoJsZmJPiDzg36BFU1hfdyzy2M4nJTOyaOPVAAet2SNjPcGDkfzla+dyojQ0iHgx0NQo0FUz14ihZgyIZBtf7vpVfequF1+WLAF+/icTM1sS+raD5XXsJHSH/b72kuefnyazgRw40DJ8zl3wgCp7JEJZ74yYznvbQiEk4x36P6XQ9VLcr5oJH8TxZuq1V/1+l1xGPnoq8hh+kz+E0q9c1ZDHciiyyQAxC8273eG+P7/7wxgqxSI4alNvxeMIKThcnmfJ7dRq/S6FGzU4d9JxhF775k2ma0VutdVZSWlN4Zak6z4v7RnCPwJf5Rlh4Tn2Jbk7AA6vjadjSd/yhYn69zDf+sQY8aVzRTcAESZqsEneygbPeRtxXfd1pAMWl/CtyeTYhAEUmu7k67zdAlFHv2mMUKRibNn7wiw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
