travis:
  secure:
    BINSTAR_TOKEN: BbJS0n4B9+sOT1IU/ejh+FVIrA5caKBAQhT97XELjzfEMHdrdUFEzskqgVgeT9dOWoWNBY+nY3CMx9Jx8+JMvK4vJDBCo12uKNbfRt7/ZUHKTsS/9+kW1D2A2C2pM5cbvEuzz9OvTErl9B5UAuxMPOMyKE5t8alju6cekciS6F7e4jjtblZ+2WT8HwYjzNF5NnSxPnNQLSpYcDO2VRFwG/eCgmN/VRYfBuI/Fwrws1dIHJe/TOW/vQvyMluxONmhCHpCnsDXvtSLxtFm9ZoOj89xsqHio3wRP1pDiX27u6oeeCTPWgQQkqkM6ZwB08wp0oERyI26M+uDCf9kfbGBmkgSdxPH6l3XhL9P+wz/DqkleAqhN1YbhklbRBPcPuwtlDVFwWUgBp8+SfJRbaLjPNczMDhiIpskVgYPaavpm3NS4ihYflr7Cf2V7izr8m9ecbQzFwXg5YtJScWzxMvXu98SxoVUtwyup86sZcjLW1fBvfS2yYWNsDknGF03Rn71hNfnGm9GUQK0YYsH7rWCsOsQCNrdDJ91PxhsuPla7UfFfi9CacmvZkBq/G+OdmaGi8zy9VIMKzK7hiM6EpSqhO6ottUDfzFoOzjCFR2CjoJZe1ppvEfh07UuJqgxajVuOaNONYqj4Gtn2FInjhFvvBOvvw4EeTPNXSyy+Q4hfLU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
