travis:
  secure:
    BINSTAR_TOKEN: R6Xo7h7eV929LohGOl7069/OsO6Pkg5d0K9auwWKiFfKC3DxSt5FIQPhr9/5pYwTh5o08ypasjptSrgLCnReYovM2eTlnJenqZDoekZAW0gQraXx4pS7GJuPEGCrbjT3aGVN/3KUAKPPfIHSmdU5OcAwNjQtfyPvXEAZZiHm80bsOYIm9BR97AbG688ZZDOiVbf+O2EdjnqQB8kYA4RLKFn8S/nZD9QaKrdB9KMyP7HJd3kPc9Zx2CkBJHyyjvrbLYWpReCEBZ2rVNGwcLh33OM1Dug0f1cjNbLKpu0jYNp//XQU2TTjhWTG53H26pHmVaAcHFjkDcCGD7Ht0tPywxIastLUsv6qbVEKGZ5whGHjT88xMyR9UuFVFsNYpuO0IlDIoT/QerWZyGKD5go2aa7mE3khG3n+kXiB30cbX4WezkHZ3YoM44QblXu9ifQToZ3X+R0QCfzyZWIfuDCULJyp3PMgIO+MSP0kEJEF+6SMEpS3vsNQtMm+HgH+F0nImjDyNM5DbnO0hBlSe0+TPgKa4shA04N4LTVLYUfKRcYCGfwM97IEZdn0IxYGc5Z1vlFXjrI6E7jfs14KQrJC9y4A66r+HKaMqUQXGmno9+dWc0F1mmrpwOe1MnlBPE+3vgo56o2TpLYT/+Nc1In9gbMy4Ybj+OzbK92iouvAcyE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
