travis:
  secure:
    BINSTAR_TOKEN: ownMtYmmMBeaLiw8VkJPANuhDIiKe2JSFvJ9XySygaBe1j29c5GtbhFalXDprhg50Tf6R5WaKWrDISHCO7U980g4q0AaGMkhMv/qQk5WcJq9nlCHZ4U3mwCjFiOAKtQKVDcm8oOdJz25i4UJRKS2y/GXAFCtYjYIfLAQuf2CsFtFlg1yPk8VsNgUzzPm6Yf0DMONzGw6esvjc8c6Ho4smwwoOupLri8nJzV9MABAMdPhlMi1uVWffcm6LwlvQT0yJO2gehjRfBshrb17JllgjJggS9LY/XHhdhWdxMcG3d4kIl9xLLBMLLgEmoZB6RjZq2MUt4DaeOhUIoDLKBXKF9wHKfKqbQJbV4hpOAmo1fbrVQyyPZ8CxoHSQDHshZUkPgfkuqvMNJFY3YkENqyB4nLQ1H21ztrwtzFX87bVzydRWvKBOOiPaq2FsRRP7SeKvSOb86XfSKyq/+B8snsoNVOIFLuqXEowomdrQ3ibcWQ3KMoa3U+MS9HpyMuXn6LpVUstGmapD9f2yexPufy5C7zkuJwbN3T8EShU/+LNhOLoI4SvYcQ2ZnK5rBE/qUW7Wh2WxZIe0CtBbts6gHVY0uNWfa8PdZTvSXJnClhiRJjhpv57Z50X4gdz656iyUAFlhyE3RDu73sqoUswECE6DzAeldUPoI4izoWuwDpqMBU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
